#!/bin/bash

# Memory Integrity Enforcement Mode Switcher
# Usage: Set MEMORY_ENFORCEMENT_MODE environment variable to "full" or "soft"

set -e

PROJECT_DIR="${PROJECT_DIR:-$PWD}"
ENTITLEMENTS_DIR="${PROJECT_DIR}/OOMBoundary"
MODE="${MEMORY_ENFORCEMENT_MODE:-soft}"

echo "🔧 Switching Memory Integrity Enforcement Mode to: ${MODE}"

case "${MODE}" in
    full|FULL|Full)
        SOURCE="${ENTITLEMENTS_DIR}/OOMBoundary-Full.entitlements"
        TARGET="${ENTITLEMENTS_DIR}/OOMBoundary.entitlements"
        echo "✅ Using Full Mode entitlements"
        ;;
    soft|SOFT|Soft|default|DEFAULT)
        SOURCE="${ENTITLEMENTS_DIR}/OOMBoundary-Soft.entitlements"
        TARGET="${ENTITLEMENTS_DIR}/OOMBoundary.entitlements"
        echo "✅ Using Soft Mode entitlements"
        ;;
    *)
        echo "⚠️  Unknown mode: ${MODE}. Using Soft Mode as default."
        SOURCE="${ENTITLEMENTS_DIR}/OOMBoundary-Soft.entitlements"
        TARGET="${ENTITLEMENTS_DIR}/OOMBoundary.entitlements"
        ;;
esac

if [ -f "${SOURCE}" ]; then
    cp "${SOURCE}" "${TARGET}"
    echo "📝 Copied ${SOURCE} to ${TARGET}"
else
    echo "❌ Error: Source entitlements file not found: ${SOURCE}"
    exit 1
fi

# Create BuildMode.txt for runtime detection
BUILD_MODE_FILE="${ENTITLEMENTS_DIR}/BuildMode.txt"
case "${MODE}" in
    full|FULL|Full)
        echo "Full Mode Build" > "${BUILD_MODE_FILE}"
        ;;
    soft|SOFT|Soft|default|DEFAULT)
        echo "Soft Mode Build" > "${BUILD_MODE_FILE}"
        ;;
    *)
        echo "Standard Build" > "${BUILD_MODE_FILE}"
        ;;
esac
echo "📄 Created ${BUILD_MODE_FILE} with mode: ${MODE}"

# Also create a Swift file with the build mode (compile-time constant)
BUILD_MODE_SWIFT="${ENTITLEMENTS_DIR}/BuildModeGenerated.swift"

# Determine mode string
case "${MODE}" in
    full|FULL|Full)
        MODE_STRING="Full Mode Build"
        ;;
    soft|SOFT|Soft|default|DEFAULT)
        MODE_STRING="Soft Mode Build"
        ;;
    *)
        MODE_STRING="Standard Build"
        ;;
esac

cat > "${BUILD_MODE_SWIFT}" <<EOF
//
//  BuildModeGenerated.swift
//  OOMBoundary
//
//  Auto-generated by switch-memory-enforcement.sh
//  Do not edit manually
//

import Foundation

let GENERATED_BUILD_MODE = "${MODE_STRING}"
EOF
echo "📄 Created ${BUILD_MODE_SWIFT}"

echo "✨ Memory Integrity Enforcement Mode successfully set to: ${MODE}"
